### ISSUE TITLE
JS Panel crashes on several interactions

### ISSUE THREAD

**Issue by Sieboldianus** [kbuffington/Georgia#56] opened 2020-12-13 17:12 UTC
I just installed this theme, but I'll get js scrashes, the JPanel turns red with a white "Error" showing.

This happens e.g. when I click on text (artist, title), with:
```output
JScript Panel v2.4.1.1 (Georgia by Mordred)
JavaScript runtime error:
Number expected
File: %AppData%\Roaming\foobar2000\georgia\js\helpers.js
Line: 192, Col: 5

```
.. at other times, I get:
```output
JScript Panel v2.4.1.1 (Georgia by Mordred)
JavaScript runtime error:
Object doesn't support this action
File: %AppData%\Roaming\foobar2000\georgia\js\georgia-main.js
Line: 41, Col: 2
```

Anything I possibly did wrong?

**Comment by Sieboldianus** [comment] 2020-12-19 06:21
Fixed one issue by adding:

```js
function calcAgeDateString(date) {
    if ( typeof date !== 'number' )
        return;
    var str = '';
	if (date.length) {
    ...
```

**Comment by marc2k3** [comment] 2020-12-23 07:02
I think the 2nd issue is caused by resizing the window above/below 3000px wide. You can fix it by installing the very latest version of JScript Panel here:

https://github.com/marc2k3/foo_jscript_panel/releases

Then replace this code at line 41 of georgia-main.js

```
	g_tooltip = window.CreateTooltip('Segoe UI', scaleForDisplay(15));
	g_tooltip.setMaxWidth(scaleForDisplay(300));
	g_tooltip.text = '';	// just in case
```

with

```
	if (!g_tooltip) {
		g_tooltip = window.CreateTooltip();
	}
	window.SetTooltipFont('Segoe UI', scaleForDisplay(15));
	g_tooltip.SetMaxWidth(scaleForDisplay(300));
	g_tooltip.text = '';	// just in case
```

**Comment by kbuffington** [comment] 2021-01-07 07:43
The second issue should be fixed out of the box in the new beta. Not sure what was causing your first issue, but let me know if it's still a problem if you can.

**Closed as completed** 2021-01-31 02:09 UTC
