### ISSUE TITLE
Wrong album art displayed after minimizing to tray.

### ISSUE THREAD

**Issue by Artins90** [kbuffington/Georgia#73] opened 2021-02-24 07:11 UTC
This could actually be a Spider Monkey Panel bug but I wouldn't know how to check.

After installing v2 beta 4 and the new SMP, if I minimize foobar to the system tray while music is playing and my playlist moves to a different album, when I maximize foobar again the album art displayed is the one from the previous album.

Clip showcasing the issue, **warning high volume:** https://streamable.com/3cw4oz

**Comment by kbuffington** [comment] 2021-02-27 08:50
I can't reproduce.

I'm wondering if it might have something to do with whatever component you're using to switch songs while minimized? It seems like it's not getting an `on_playback_new_track()` callback and so it's not checking to see if it needs to display new artwork.

Position playback a few seconds from the end of the last song on an album, and then minimize and wait for the next album to start. Then tell me if you're still having the same issue.

**Comment by Artins90** [comment] 2021-02-27 15:00
I am using the media keys on my keyboard to switch to the next track.
The small window with media controls in the upper left corner is part of Windows 10.  

I tried to let the playlist play on its own like you suggested and I was able to trigger the issue.
<img width="1702" alt="Capture" src="https://user-images.githubusercontent.com/28777957/109390866-6114ec00-7914-11eb-8127-716c6711ac8a.PNG">

This is the console output:
Components loaded in: 0:00.649781
Configuration read in: 0:00.004427
foobar2000 v1.6.4 [standard]
Watching: E:\Users\Artins\Music
Spider Monkey Panel v1.4.1 (Georgia: Georgia v2.0.0-beta4 by Mordred): initialized in 13 ms
Filter Panel - Genre: initialised in 0.001 s
Filter Panel - Artist: initialised in 0.001 s
User Interface initialized in: 0:00.110293
foo_enhanced_playcount: loaded
FFmpeg version: 4.3.1
Querying last.fm: http://ws.audioscrobbler.com/2.0/?method=user.getRecentTracks&api_key=a1685abe5265b93cf2be4a70d181bf6b&user=artins90&limit=200&format=json&from=1614296602&page=1
Startup time : 0:00.864541
in on_init()
in on_size() => width: 3835, height: 1971
Playlist initialized in 7ms
Georgia loaded in 888ms
Playlist initialized in 5ms
Current released version of Georgia: v2.0.0-beta4
You are on the most current version of Georgia
Querying last.fm: http://ws.audioscrobbler.com/2.0/?method=user.getTrackScrobbles&api_key=a1685abe5265b93cf2be4a70d181bf6b&user=artins90&artist=LiSA&track=Believe in ourselves&limit=200&format=json&page=1
Querying last.fm: http://ws.audioscrobbler.com/2.0/?method=user.getTrackScrobbles&api_key=a1685abe5265b93cf2be4a70d181bf6b&user=artins90&artist=LiSA&track=WiLL ~無色透明~&limit=200&format=json&page=1
Found 1 scrobbles in last.fm (since last known scrobble at 2021-02-08 23:44:06) of "WiLL ~無色透明~"
Found 1 scrobbles in last.fm (since last known scrobble at 2021-02-16 02:31:50) of "Believe in ourselves"
on_metadb_changed()
Opening track for playback: "E:\Users\Artins\Music\LiSA - LEO-NiNE - 13 - BEAUTIFUL WORLD.flac"
Fetching new art
Device: Speakers (Realtek High Definition Audio)
Mix format: 96000 Hz / 32-bit float / 2 channels (0x3)
Sending stream: 96000 Hz / 32-bit float / 2 channels (0x3)
on_metadb_changed()
lastfm: [1602938746000, 1603009476000, 1603034302000, 1603055927000, 1603133215000, 1603276813000, 1603385251000, 1603835183000, 1604518833000, 1604797939000, 1605020297000, 1605106035000, 1605907774000, 1606205697000, 1606949832000, 1607188275000, 1607790648000, 1607940055000, 1608068441000, 1608234128000, 1608956008000, 1609245241000, 1609518166000, 1609686472000, 1609793737000, 1609913283000, 1610086307000, 1610244447000, 1610585089000, 1611144414000, 1611249001000, 1611770312000, 1612368248000, 1612833104000, 1612894137000, 1613246348000, 1613431725000, 1613517976000, 1613884922000, 1614059444000, 1614246205000]
foobar: [1602938747000, 1603009477000, 1603034303000, 1603055929000, 1603133216000, 1603276814000, 1603835184000, 1604518834000, 1604797940000, 1605020298000, 1605106036000, 1605471868000, 1605907775000, 1606205698000, 1606949833000, 1607188277000, 1607790649000, 1607940057000, 1608068442000, 1608234129000, 1608956009000, 1609245242000, 1609518167000, 1609686473000, 1609793738000, 1609913284000, 1610086309000, 1610244448000, 1610585090000, 1611144448000, 1611249004000, 1611770314000, 1612368249000, 1612833105000, 1612894138000, 1613246349000, 1613431726000, 1613517977000, 1613884923000, 1613966455000, 1614059445000, 1614246206000]
Querying last.fm: http://ws.audioscrobbler.com/2.0/?method=user.getTrackScrobbles&api_key=a1685abe5265b93cf2be4a70d181bf6b&user=artins90&artist=LiSA&track=BEAUTIFUL WORLD&limit=200&format=json&page=1
Found 0 scrobbles in last.fm (since last known scrobble at 2021-02-25 10:43:25) of "BEAUTIFUL WORLD"
Opening track for playback: "E:\Users\Artins\Music\LiSA - dawn - 01 - dawn.flac"
on_metadb_changed()
lastfm: [1610990498000, 1610991348000, 1611096079000, 1611144759000, 1611522053000, 1611770625000, 1611883595000, 1612368560000, 1612833417000, 1612894450000, 1613432037000, 1613518288000, 1613885234000, 1613966229000, 1614059756000, 1614246517000]
foobar: [1610990500000, 1610991350000, 1611096081000, 1611144760000, 1611522054000, 1611770626000, 1611883596000, 1612368561000, 1612833418000, 1612894451000, 1613245937000, 1613432039000, 1613518289000, 1613885235000, 1613966232000, 1614059757000, 1614246518000]
Querying last.fm: http://ws.audioscrobbler.com/2.0/?method=user.getTrackScrobbles&api_key=a1685abe5265b93cf2be4a70d181bf6b&user=artins90&artist=LiSA&track=dawn&limit=200&format=json&page=1
Found 0 scrobbles in last.fm (since last known scrobble at 2021-02-25 10:48:37) of "dawn"


There is "fetching new art" after the first track (window maximized), 

Opening track for playback: "E:\Users\Artins\Music\LiSA - LEO-NiNE - 13 - BEAUTIFUL WORLD.flac"
Fetching new art

But it's missing after the second track (window minimized to tray) 
Opening track for playback: "E:\Users\Artins\Music\LiSA - dawn - 01 - dawn.flac"  
on_metadb_changed()

**Comment by kbuffington** [comment] 2021-03-01 08:12
Okay, your leg helped me finally figure this out. 

The issue is that you're using embedded artwork and your files are in the same folder. Doesn't actually have to be minimized to exhibit this issue. Now if you load your art embedded, I will always call `fetchNewArtwork` on a new track. Will be fixed in 2.0 release. Thanks for reporting!

**Closed as completed** 2021-03-01 08:15 UTC
Labels: bug

**Comment by Artins90** [comment] 2021-03-01 10:43
I tested v2.0 and I confirm that the issue has been fixed.
Thank you.
