### ISSUE TITLE
Crash on 4k/1080p monitor pair

### ISSUE THREAD

**Issue by klercke** [kbuffington/Georgia#52] opened 2020-10-12 20:37 UTC
I tried installing Georgia on my work computer today and it crashes on startup. I can make the crash stop by removing "auto" from the "detect 4k" field, but everything gets very small. If I reload after the crash, the theme will load. I'm using the latest version of everything and am attempting to run fb2k on my 1080p monitor (there is a 4k monitor on the system though).

**Comment by doublebuffered** [comment] 2020-11-07 23:30
I had the same issue with a dual monitor setup, it works when I initially load but each time I drag the window it crashes. To get around this and force it into 4k mode, I replaced auto with always in the properties

**Comment by klercke** [comment] 2020-11-09 20:37
That worked. Thanks.

**Comment by jimmywan** [comment] 2020-11-17 18:04
FYI, I did the switch from "auto" to "always" and it fixed my startup crash.

I unplugged my second monitor and turned it back to "auto". This results in the JS error on startup returning, so I don't think it's even related to having dual monitors. I didn't experience crashes on dragging the window, but a maximize or restore will cause it to crash again.

```
JScript Panel v2.4.1.1 (Georgia by Mordred)
JavaScript runtime error:
Not implemented

File: C:\Users\jimmy\AppData\Roaming\foobar2000\georgia\js\georgia-main.js
Line: 41, Col: 2
```

For reference, this is my current setup:
```
Core (2020-10-22 15:45:46 UTC)
    foobar2000 core 1.6.2
foo_abx.dll (2019-03-11 19:32:20 UTC)
    ABX Comparator 2.0.6d
foo_albumlist.dll (2020-10-22 15:45:04 UTC)
    Album List 4.7
foo_cdda.dll (2020-10-22 15:45:02 UTC)
    CD Audio Decoder 1.6.2
foo_chronflow.dll (2020-05-21 20:35:50 UTC)
    Coverflow 0.5.2
foo_converter.dll (2020-10-22 15:45:08 UTC)
    Converter 1.6.2
foo_dsp_eq.dll (2020-10-22 15:44:58 UTC)
    Equalizer 1.2.2
foo_dsp_std.dll (2020-10-22 15:44:58 UTC)
    Standard DSP Array 1.6.2
foo_dumb.dll (2018-03-06 08:49:23 UTC)
    DUMB module decoder 2.0.3
foo_dynamic_range.dll (2016-09-13 05:19:16 UTC)
    Dynamic Range Meter 1.1.1
foo_enhanced_playcount.dll (2019-12-21 03:45:47 UTC)
    Enhanced Playback Statistics 4.2.1
foo_fileops.dll (2020-10-22 15:45:04 UTC)
    File Operations 1.6.2
foo_freedb2.dll (2020-10-22 15:45:02 UTC)
    Online Tagger 0.8
foo_input_dsdiff.dll (2018-03-06 08:49:23 UTC)
    DSDIFF Decoder 1.6
foo_input_shorten.dll (2016-09-13 05:19:16 UTC)
    Shorten decoder 0.4.2.3
foo_input_std.dll (2020-10-22 15:45:32 UTC)
    FFmpeg Decoders 4.3.1
    Standard Input Array 1.6.2
foo_jscript_panel.dll (2020-08-31 12:26:52 UTC)
    JScript Panel 2.4.1.1
foo_out_asio.dll (2016-09-13 05:19:16 UTC)
    ASIO support 2.1.2
foo_out_wasapi.dll (2017-10-30 02:11:56 UTC)
    WASAPI output support 3.3
foo_playcount.dll (2020-07-01 22:00:50 UTC)
    Playback Statistics 3.0.4
foo_rgscan.dll (2020-10-22 15:45:08 UTC)
    ReplayGain Scanner 1.6.2
foo_ui_columns.dll (2020-09-04 02:55:18 UTC)
    Columns UI 1.6.0
foo_ui_std.dll (2020-10-22 15:45:14 UTC)
    Default User Interface 1.6.2
foo_uie_lyrics3_minilyrics.dll (2020-02-06 00:54:48 UTC)
    MiniLyrics source 0.9.1
foo_unpack.dll (2020-10-22 15:45:04 UTC)
    ZIP/GZIP/RAR/7-Zip Reader 1.6.2
```

**Comment by kbuffington** [comment] 2021-01-07 07:41
Duplicate of #56.

**Closed as completed by kbuffington** 2021-01-07 07:41 UTC
