### ISSUE TITLE
Album Art Displaying in Low Resolution

### ISSUE THREAD

**Issue by t-cth** [kbuffington/Georgia#54] opened 2020-11-21 18:59 UTC
For some reason the album art always displays in very low resolution. All of my albums are using album art that's at least 600x600, but the now playing display is much lower than that.

**Comment by kbuffington** [comment] 2020-11-24 21:42
Is Options >> Cycle Through All Artwork enabled? What do you name your artwork? Do you have embedded artwork? What resolution is your screen? Is it possible you have hidden artwork in your folders downloaded by some other player?

**Comment by t-cth** [comment] 2020-11-26 03:11
- I've tried with the option checked and unchecked. No difference.
- All artwork files are named "cover.jpg" and placed in the album folder, and is embedded in the track files themselves. 
- The issue happens on both a 2560x1440 monitor and a 3840x2160 laptop display,
 - I've used f2k exclusively for 8 years, so there's no hidden or additional artwork.

Thanks!

**Comment by Vertgear** [comment] 2020-12-16 22:12
I have the same issue, sometimes it loads a low-res cover and sometimes the correct high-res, and whenever I open "Show Playlist" or "Show Library" the cover instantly changes to low-res from high-res. 

Checking and uncheking repeatedly "Cycle Through All Artwork" causes the artwork to switch the quality, going through 2-4 different resolutions. 

All my artwork are in the folder with files, named cover.jpg or folder.jpg; The covers are usually 1000x1000, up too 1400x1400.

Cheers

**Comment by kbuffington** [comment] 2021-01-07 07:38
Can one of you see if the problem still occurs in the new 2.0.0-beta1?

**Comment by Vertgear** [comment] 2021-01-07 22:33
Seems to still persist, I have now a video showing it

https://user-images.githubusercontent.com/23695044/103951036-41481f80-513e-11eb-898e-3ab9095419f7.mp4

In the previous version I have seemingly fixed the half of the problem so that the cover doesn't reduce resolution when opening/closing Library/Playlist by re-ordering cover path in global.js, moving `'$replace(%path%,%filename_ext%,)cover*',` to the top
https://i.imgur.com/lV3scxb.png

Video of the "fix"

https://user-images.githubusercontent.com/23695044/103951894-c122b980-513f-11eb-8ed9-8d86f488b104.mp4

Did not yet try to reorder in the new version.

**Comment by kbuffington** [comment] 2021-01-08 01:01
Damn, but those videos are very helpful. Two things:
1) Do the files in question have embedded artwork and if so, what's the resolution? I suspect this could be the problem.
2) Can you edit georgia-main.js and on line 2544 (right after the line that starts `aa_list = [... new Set(aa_list)].filter` add this line:
```
		console.log('>>> Album art list:', aa_list, '<<<');
``` 
And then play a song that's experiencing this issue and paste me the logged output in the console between the `>>>` and `<<<`

**Comment by Vertgear** [comment] 2021-01-08 01:09
1. The artwork for the song shown is not embedded, just a cover.jpg (1400x1400) file in the directory
2. `>>> Album art list: ["E:\Music\Not-Touhou\Devil Within - DARK SUPREMACY [FLAC]\Folder.jpg", "E:\Music\Not-Touhou\Devil Within - DARK SUPREMACY [FLAC]\cover.jpg", "E:\Music\Not-Touhou\Devil Within - DARK SUPREMACY [FLAC]\AlbumArtSmall.jpg"] <<<`

**Comment by kbuffington** [comment] 2021-01-08 06:59
Okay, so the problem is that `E:\Music\Not-Touhou\Devil Within - DARK SUPREMACY [FLAC]\AlbumArtSmall.jpg"` file it's picking up in the folder. Not sure where that came from or whether it's hidden, but that's why it's showing the low-rez version. Remove those from the folder and the problem will be solved.

**Comment by Vertgear** [comment] 2021-01-08 14:45
Okay, found and deleted those files, turns out they were files created by WindowsMusicPlayer, the Folder.jpg and AlbumArtSmall.jpg

They were hidden as a "protected operating system file", cleaned all hidden files from my music directories with CMD and it's working as intended now.

 _fuck WindowsMusicPlayer_

**Comment by kbuffington** [comment] 2021-01-08 15:42
Yeah, that's kinda what I suspected. WMP adds tons of hidden images to folders for some reason. Pretty annoying stuff. Will be closing this, and @4x4Strings can reopen if he's somehow having a different problem.

**Closed as completed by kbuffington** 2021-01-08 15:42 UTC
